repos:
- repo: https://github.com/astral-sh/uv-pre-commit
  # This makes sure that uv.lock is up to date when pyproject.toml
  # is changed
  rev: 0.8.22
  hooks:
    - id: uv-lock
- repo: https://github.com/asottile/pyupgrade
  rev: v3.20.0
  hooks:
    - id: pyupgrade
      args: [--py310-plus]
      files: '^(litebird_sim)/.*\.py$'
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.13.0
  hooks:
    # Run the linter.
    - id: ruff
      types_or: [ python, pyi, jupyter ]
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
      types_or: [ python, pyi, jupyter ]
