# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
   os: ubuntu-22.04
   tools: {python: "3.12"}

python:
  install:
    - method: pip
      path: .

  system_packages: true

build:
  jobs:
    pre_install:
      - pip install poetry poetry-plugin-export
      - poetry export -f requirements.txt --without-hashes --output requirements.txt

sphinx:
  configuration: docs/source/conf.py
