
[map_based_sims]

  [map_based_sims.general]
  save = false
  nside = 16
  gaussian_smooth = true
  bandpass_int = true
  parallel_mc = false
  coadd = true

  [map_based_sims.noise]
  make_noise = true
  nmc_noise = 1
  seed_noise = 6437
  N_split = 1

  [map_based_sims.cmb]
  make_cmb = true
  cmb_ps_file = false
  cmb_r = 0
  nmc_cmb = 1
  seed_cmb = 38198

  [map_based_sims.fg]
  make_fg = true
  dust = 'pysm_dust_0'
  synch = 'pysm_synch_0'
  freefree =  'pysm_freefree_1'
  ame =  'pysm_ame_1'

  [map_based_sims.output]
  output_directory = './test_mbs'
  output_string = 'test'
